#!/bin/bash

# mysql
export DB_URL="jdbc:mysql://YOUR-CONNECTION"
export DB_USERNAME="YOUR-DB-USERNAME"
export DB_PASSWORD="YOUR-DB-PASSWORD"

# midtrans
export MERCHANT_ID="YOUR-MERCHANT-ID"
export CLIENT_KEY="YOUR-CLIENT-KEY"
export SERVER_KEY="YOUR-SERVER-KEY"

# mailtrap
export MAILTRAP_USERNAME="YOUR-MAILTRAP-USERNAME"
export MAILTRAP_PASSWORD="YOUR-MAILTRAP-PASSWORD"