server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      idle-timeout: 300000
      minimum-idle: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb  # Set the storage engine to InnoDB
    open-in-view: false

application:
  external-service:
    # configure for payment gateway
    payment-gateway:
      midtrans:
        merchant-id: ${MERCHANT_ID}
        client-key: ${CLIENT_KEY}
        server-key: ${SERVER_KEY}
        base-url: "https://api.sandbox.midtrans.com"
        payment-uri: "https://api.sandbox.midtrans.com/v2/charge"
        payment:
          charge: "/v2/charge"
        disbursement:
          beneficiaries: "/api/v1/beneficiaries"
          patch-beneficiaries: "/api/v1/beneficiaries/alias_name"
          list-beneficiaries: "/api/v1/beneficiaries"
          payouts: "/api/v1/payouts"
          approve-payouts: "/api/v1/payouts/approve"
          reject-payouts: "/api/v1/payouts/reject"
          detail-payouts: "/api/v1/payouts/reference_no"
          transaction-details: "/api/v1/statements"

    # configure for email gateway
    email-gateway:
      mail-dev:
        hostname: sandbox.smtp.mailtrap.io
        port: 2525
        username: 875267a6737bd0
        password: e4f97898f46aa3
        sender: payment-platform@testmail.com