server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_midtrans
    username: root
    password: Codespace
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      idle-timeout: 300000
      minimum-idle: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        # dialect: org.hibernate.dialect.MySQLDialect
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb  # Set the storage engine to InnoDB
    open-in-view: false

application:
  external-service:
    # configure for payment gateway
    payment-gateway:
      midtrans:
        merchant-id: G122340993
        client-key: SB-Mid-client-IkH9QUB3A8t8WLLk
        server-key: SB-Mid-server-9D9fBs9eVq_N9WFk0ZOZebEO
        base-url: "https://api.sandbox.midtrans.com"
        payment-uri: "https://api.sandbox.midtrans.com/v2/charge"
        payment:
          charge: "/v2/charge"
        disbursement:
          beneficiaries: "/api/v1/beneficiaries"
          patch-beneficiaries: "/api/v1/beneficiaries/alias_name"
          list-beneficiaries: "/api/v1/beneficiaries"
          payouts: "/api/v1/payouts"
          approve-payouts: "/api/v1/payouts/approve"
          reject-payouts: "/api/v1/payouts/reject"
          detail-payouts: "/api/v1/payouts/reference_no"
          transaction-details: "/api/v1/statements"

    # configure for email gateway
    email-gateway:
      mail-dev:
        hostname: localhost
        port: 1025
        username: root
        password: root
        sender: payment-platform@testmail.com