server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        storage_engine: innodb  # Set the storage engine to InnoDB
    open-in-view: true

springdoc:
  api-docs:
    version: OPENAPI_3_0
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
    disable-swagger-default-url: true

application:
  external-service:
    # configure for payment gateway
    payment-gateway:
      midtrans:
        merchant-id: ${MERCHANT_ID}
        client-key: ${CLIENT_KEY}
        server-key: ${SERVER_KEY}
        # hostname default
        hostname: "https://api.sandbox.midtrans.com"
        # payment for coreapi midtrans
        core-api:
          charge: "/v2/charge"


        payment-uri: "https://api.sandbox.midtrans.com/v2/charge"
        payment:
          charge: "/v2/charge"
        disbursement:
          beneficiaries: "/api/v1/beneficiaries"
          patch-beneficiaries: "/api/v1/beneficiaries/alias_name"
          list-beneficiaries: "/api/v1/beneficiaries"
          payouts: "/api/v1/payouts"
          approve-payouts: "/api/v1/payouts/approve"
          reject-payouts: "/api/v1/payouts/reject"
          detail-payouts: "/api/v1/payouts/reference_no"
          transaction-details: "/api/v1/statements"

    # configure for email gateway
    email-gateway:
      mail-dev:
        hostname: sandbox.smtp.mailtrap.io
        port: 2525
        username: ${MAILTRAP_USERNAME}
        password: ${MAILTRAP_PASSWORD}
        sender: store.example.notification@noreply.com

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.resource.transaction: WARN
    org.apache.catalina.core.AprLifecycleListener: WARN
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: OFF
    com.zaxxer.hikari: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"